services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/project/notebooks
      - ./data:/project/data
    environment:
      - JUPYTER_TOKEN=yourToken