version: '3.5'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/project/notebooks
      - ./data:/project/data
    environment:
      - JUPYTER_TOKEN=yourToken
    networks:
      san-ba_mynetwork:
        ipv4_address: 172.23.0.8

networks:
  san-ba_mynetwork:
    external: true
